### ISSUE TITLE
broken in DCAF 1.1

### ISSUE THREAD

**Issue by brbrindle** [LabVIEW-DCAF/Scaling-Polynomial#1]
Error message when attempting to configure module:
Dev Error: The Ui.vi for the selected class is broken

**Comment by pollockm** [comment]
I'll look into this.  Thanks for the report!

**Comment by pollockm** [comment]
Should be fixed now.  Main fixes are in the Scaling parent package.  We should be pushing the packages out to the public VIPM repository today or tomorrow.

Thanks again for letting us know!

Fixed in https://github.com/LabVIEW-DCAF/Scaling-Polynomial/commit/1df0b59a82485c860b949c6527759a76ba46dd51

**Comment by pollockm** [comment]
FYI, testing revealed another issue.  tracked as https://github.com/LabVIEW-DCAF/Scaling/issues/9

The issue of not being able to load the UI is fixed, there is some residual buggy behavior from the table api modifications that needs to be fixed today before the updates can roll out on VIPM.

**Comment by pollockm** [comment]
And the above is now fixed as well.  We should be back to parity level with previous release.  My apologies for the bug.  If you see any more bugs, we'd love to hear about them so we can squash those as well.
